global:
  scrape_interval:     15s 
scrape_configs:
  - job_name: 'prometheus-dotnet-scrape'
    scrape_interval: 5s
    metrics_path: '/metrics' 
    static_configs:
      - targets: ['localhost:10000']